version: "3"
services:
  db:
    image: postgres:10.4-alpine
    container_name: anatolii-test-app-db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/lib/postgresql:/var/lib/postgresql
      - ./db_data/log/postgresql:/var/log/postgresql
      - ./db_data/etc/postgresql:/etc/postgresql
    environment:
      POSTGRES_USER: tl
      POSTGRES_PASSWORD: tl
      POSTGRES_DB: tl
  web:
    build: .
    image: anatolii-test-app
    container_name: anatolii-test-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/opt/anatolii-test-app
